`:icons: font

== README

This repository contains the source for the textbook https://start-concurrent.github.io[Start Concurrent: A Gentle Introduction to Concurrent Programming].  It is licensed under  https://github.com/start-concurrent/start-concurrent.github.io/blob/master/LICENSE[Apache License 2.0].

=== Software Needed

==== Basic Software Needed

. https://git-scm.com/downloads[Git] (and a https://github.com[GitHub] account to access the
https://github.com/start-concurrent/start-concurrent.github.io[Start Concurrent repository])
. https://www.ruby-lang.org/en/downloads/[Ruby]
. https://asciidoctor.org[Asciidoctor]
. https://github.com/asciidoctor/asciidoctor-mathematical[Asciidoctor-Mathematical]
. https://github.com/wshito/asciidoctor-chunker[Asciidoctor Chunker] (to convert to HTML chunks)
. https://github.com/jirutka/asciidoctor-rouge[Asciidoctor Rouge] (for syntax highlighting)
. https://asciidoctor.org/docs/asciidoctor-pdf/[Asciidoctor PDF gem] (to generate a PDF version)

=== Editing the Illustrations

Most (all?) "`figures`" in the book are https://www.adobe.com/products/illustrator.html[Adobe Illustrator] documents saved in PDF format, and are located in the `figures` subdirectory of the chapter in which they appear.  For each PDF file, there is a corresponding SVG file located in the `images` subdirectory.  The SVG file is what is imported into the AsciiDoc file.

To create a new figure or edit an existing one...

. Create or edit the Illustrator file in the figures subdirectory.
. Save changes using the default (PDF) format.
. Temporarily, convert all text to outlines:
.. `Select > Select All`
.. `Type > Create Outlines`
. Then, `Save a Copy As...`, using SVG format and deselecting the "`Preserve Illustrator Editing Capability`", to create an .SVG file in the `images` subdirectory.

Note: Don't save the outlined text version back to the original PDF file!

=== Generating the HTML Files

See the shell script `update-html` and companion ruby script `update-html.rb`.  The shell script generates both the full book as a single-page html file and a "chunked" version that generates one chapter per html file (for faster downloading).

=== Generating the PDF

See the shell script `update-pdf` and companion ruby script `update-pdf.rb`.

==== Special Workaround for Tables when Generating PDF

WARNING: This section has not been updated lately and a permanent fix may now be in place.

There is a bug in the https://github.com/prawnpdf/prawn-table[prawn-table] code used by Asciidoctor-PDF when formatting certain tables.  There is discussion and a (so-far incomplete) fix https://discuss.asciidoctor.org/Problem-using-Asciidoctor-PDF-to-format-wide-autowidth-table-header-cells-td7220.html[here].

Steps to fix the problem (simplified to not use a Gemfile):

. Download the latest prawn-table code to a separate repository.
.. `git clone https://github.com/prawnpdf/prawn-table.git`
.. `cd prawn-table`
. Build and install.
.. `gem build prawn-table.gemspec`
.. `gem install prawn-table-0.2.3.gem`

These steps do not fix all tables.  Specifically, not all tables with autowidth will work.  Advice
from the Asciidoctor https://discuss.asciidoctor.org/Problem-using-Asciidoctor-PDF-to-format-wide-autowidth-table-header-cells-tp7220p7229.html[authority] is to use column ratios and table width.

=== Generating E-Book Formats

WARNING: In progress.

. Update book sources to comply with required format. (One time; in progress.)
. Install the https://asciidoctor.org/docs/asciidoctor-epub3/[AsciiDoctor EPUB3 gem].
. Run Asciidoctor EPUB3 to do the conversion: +
`$ (cd full; asciidoctor-epub3 index.adoc -D ../epub3)`
. Additional steps (TBD) convert the document to Kindle format (KF8/MOBI).

Other gems needed (apparently):

* https://rubygems.org/gems/gepub[gepub]
* https://rubygems.org/gems/epubcheck[epubcheck]
