== README

=== Software Needed

. https://git-scm.com/downloads[Git] (and a https://github.com[GitHub] account to access the
https://github.com/start-concurrent/start-concurrent.github.io[Start Concurrent repository])
. https://pandoc.org[Pandoc] (to convert from LaTeX)
. https://asciidoctor.org[Asciidoctor]
. https://www.ruby-lang.org/en/downloads/[Ruby]
. https://github.com/wshito/asciidoctor-chunker[Asciidoctor Chunker] (to convert to HTML chunks)
. https://github.com/roswell/roswell[Roswell] (needed by Asciidoctor Chunker)

=== Converting Chapters from LaTeX

These are the steps I used to convert chapter 1.

. Converted LaTeX to AsciiDoc using +
``$ cd WhateverChapter
``$ pandoc WhateverChapter.tex -t asciidoc -o index.ad --atx-headers`` +
and a lot of editing.  Pandoc doesn't handle the imported figures (they're dropped) and latexmath:[$xyz$] must be converted to stem:[xyz].
. Converted images from PDF to png, e.g., using `convert`: +
``$ convert -density 600 figures/vonNeumann.pdf images/vonNeumann.png``
The density of 600 is better than 300, but still not as elegant as using svg or pdf directly.

I tried using <embed> and <object> in "pass" mode (an AsciiDoc feature that allows passing
html through), but the results are not satisfactory (see below)
and browser dependent.  Seems like svg would be better, but I don't know what tools yet to use.

Using embed...

pass:[<embed src="chapters/01-computer-basics/figures/vonNeumann.pdf" width=800/>]

Using object...

pass:[<object data="chapters/01-computer-basics/figures/vonNeumann.pdf" width=800>Missing</object>]

=== Generating an HTML File per Chapter

. Install https://github.com/wshito/asciidoctor-chunker[Asciidoctor Chunker], including
https://github.com/roswell/roswell[Roswell].
. Create the HTML version of the book in the usual way.
. Convert using Asciidoctor Chunker (with ascidoctor-chunker.ros in your path): +
``$ asciidoctor-chunker.ros index.html -o chunked``
