== README

This repository contains the source for the textbook https://start-concurrent.github.io[Start Concurrent: A Gentle Introduction to Concurrent Programming].  It is licensed under  https://github.com/start-concurrent/start-concurrent.github.io/blob/master/LICENSE[Apache License 2.0].

=== Software Needed

. https://git-scm.com/downloads[Git] (and a https://github.com[GitHub] account to access the
https://github.com/start-concurrent/start-concurrent.github.io[Start Concurrent repository])
. https://asciidoctor.org[Asciidoctor]
. https://www.ruby-lang.org/en/downloads/[Ruby]
. https://github.com/wshito/asciidoctor-chunker[Asciidoctor Chunker] (to convert to HTML chunks)
. https://github.com/roswell/roswell[Roswell] (needed by Asciidoctor Chunker)

=== Generating the HTML File

``$ asciidoctor index.adoc``

=== Generating an HTML File per Chapter

. Install https://github.com/wshito/asciidoctor-chunker[Asciidoctor Chunker], including
https://github.com/roswell/roswell[Roswell].
. Create the full HTML version of the book: +
`(cd full; asciidoctor index.adoc -o index.html)`
. Convert using Asciidoctor Chunker (with `ascidoctor-chunker.ros` in your path): +
`$ asciidoctor-chunker.ros full/index.html -o chunked`

A UNIX script to update both the full and chunked versions of the HTML is located in the root directory (`update-html`).

=== Generating the PDF

. Install the https://asciidoctor.org/docs/asciidoctor-pdf/[Asciidoctor PDF gem].
. Run Asciidoctor PDF to do the conversion: +
`$ (cd full; asciidoctor-pdf index.adoc)`
