:icons: font

== README

This repository contains the source for the textbook https://start-concurrent.github.io[Start Concurrent: A Gentle Introduction to Concurrent Programming].  It is licensed under  https://github.com/start-concurrent/start-concurrent.github.io/blob/master/LICENSE[Apache License 2.0].

=== Software Needed

. https://git-scm.com/downloads[Git] (and a https://github.com[GitHub] account to access the
https://github.com/start-concurrent/start-concurrent.github.io[Start Concurrent repository])
. https://asciidoctor.org[Asciidoctor]
. https://www.ruby-lang.org/en/downloads/[Ruby]
. https://github.com/wshito/asciidoctor-chunker[Asciidoctor Chunker] (to convert to HTML chunks)
. https://github.com/roswell/roswell[Roswell] (needed by Asciidoctor Chunker)

=== Editing the Illustrations

Most (all?) "`figures`" in the book are https://www.adobe.com/products/illustrator.html[Adobe Illustrator] documents saved in PDF format, and are located in the `figures` subdirectory of the chapter in which they appear.  For each PDF file, there is a corresponding SVG file located in the `images` subdirectory.  The SVG file is what is imported into the AsciiDoc file.

To create a new figure or edit an existing one...

. Create or edit the Illustrator file in the figures subdirectory.
. Save changes using the default (PDF) format.
. Temporarily, convert all text to outlines:
.. `Select > Select All`
.. `Type > Create Outlines`
. Then, `Save a Copy As...`, using SVG format and deselecting the "`Preserve Illustrator Editing Capability`", to create an .SVG file in the `images` subdirectory.

Note: Don't save the outlined text version back to the original PDF file!

=== Generating the HTML File

``$ asciidoctor index.adoc``

=== Generating an HTML File per Chapter

. Install https://github.com/wshito/asciidoctor-chunker[Asciidoctor Chunker], including
https://github.com/roswell/roswell[Roswell].
. Create the full HTML version of the book: +
`(cd full; asciidoctor index.adoc -o index.html)`
. Convert using Asciidoctor Chunker (with `ascidoctor-chunker.ros` in your path): +
`$ asciidoctor-chunker.ros full/index.html -o chunked`

A UNIX script to update both the full and chunked versions of the HTML is located in the root directory (`update-html`).

=== Generating the PDF

. Install the https://asciidoctor.org/docs/asciidoctor-pdf/[Asciidoctor PDF gem].
. Run Asciidoctor PDF to do the conversion: +
`$ (cd full; asciidoctor-pdf index.adoc -D ../pdf)`

=== Generating E-Book Formats

WARNING: In progress.

. Update book sources to comply with required format. (One time; in progress.)
. Install the https://asciidoctor.org/docs/asciidoctor-epub3/[AsciiDoctor EPUB3 gem].
. Run Asciidoctor EPUB3 to do the conversion: +
`$ (cd full; asciidoctor-epub3 index.adoc -D ../epub3)`
. Additional steps (TBD) convert the document to Kindle format (KF8/MOBI).

Other gems needed (apparently):
. https://rubygems.org/gems/gepub[gepub]
. https://rubygems.org/gems/epubcheck[epubcheck]
