#!/bin/sh
commands=( 
    "git -v"
    "ruby -v"
    "npm -v"
    "gem list asciidoctor"
    "npm list asciidoctor-chunker"
    "npm list asciidoctor-pdf"
    "npm list asciidoctor-mathematical"
    )

echo
for command in "${commands[@]}"; do
    echo ===== $command =====
    echo `$command`
    echo
    done
