#! /bin/bash -x
# EXPERIMENTAL/INCOMPLETE  MacOS only.
# This script installs and/or upgrades tools used to build the book.  
# It does not fully work due to setting of PATH and (perhaps) other environment variables.

brew upgrade git
brew upgrade ruby
brew upgrade npm
sudo gem install asciidoctor
sudo gem install asciidoctor-rouge

sudo gem install css_parser -v 1.12.0
sudo gem install asciidoctor-pdf
