[[chapter:Inheritance]]
:imagesdir: chapters/11-inheritance/images
== Inheritance

=== Problem: Boolean circuits

In Chapter REF=chapter:Selection, we talked extensively about Boolean
algebra and how it can be applied to `if` statements in order to control
the flow of execution in your program. The commands that we give in
software must be executed by hardware in order to have an effect. It
should not be surprising that computer hardware is built out of digital
circuits that behave according to the same rules as Boolean logic. Each
component of these circuits is called a _logic gate_. There are logic
gates corresponding to all the Boolean operations you are used to: AND,
OR, XOR, NOT, and others.

The output of an AND gate is the result of performing a logical AND on
its inputs. That is, the output is true if and only if both of the
inputs are true. The same correlation exists between each gate and the
Boolean operator with the same name. At the level of circuitry, a 1 (or
"`on`") is often used to represent true, and a 0 (or "`off`") is often
used to represent false. Modern computer circuitry is built almost
entirely out of such gates, performing addition, subtraction, and all
other basic operations as complicated combinations of logic gates, where
each digit of every number is a 1 or 0 determined by the circuit.

Because these circuits can become large and unwieldy, your problem is to
write a Java program that will allow a user to specify the design of
such a circuit and then see what its output is. The input to this
program will be a text file redirected to standard input that gives the
number of gates of the circuit, lists what each gate is, then gives a
list of connections between them.

The following is an example of input to make a circuit with six
components.

....
6
true
false
AND
XOR
NOT
OUTPUT 1
2 0 1
3 2 1
4 3
5 4
....

The first line specifies the total number of components. The next two
components give either true or false inputs, depending on their name.
The `AND` and the `XOR` correspond to gates of the same name which each
take two inputs. The `NOT` corresponds to a NOT gate with a single
input. Finally, `OUTPUT 1` is the single output of this circuit that we
are interested in. After the list of gates is a list of how they are
connected. The line `2 0 1` specifies that gate at index 2, which
happens to be an AND gate, has an input from the gate at index 0 and an
input from the gate at index 1. In other words, the AND gate has one
true input and one false input. The final circuit produced would look
like the following.

